[package]
name = "melon-rs"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0"

[dependencies]
glium = "0.32.1"
cxx = "1.0"
once_cell = "1.16.0"

[build-dependencies]
cmake = "0.1"
cxx-build = "1.0"
