key_map:
# general actions
- input:
    key_code: Comma
    modifiers: null
  action: PlayPlause
- input:
    key_code: Period
    modifiers: null
  action: Step
- input:
    key_code: S
    modifiers:
      shift: false
      ctrl: true
      alt: false
      logo: false
  action: !Save save.bin
- input:
    key_code: R
    modifiers: null
  action: QuitRecording
- input:
    key_code: D
    modifiers:
      shift: true
      ctrl: false
      alt: false
      logo: false
  action: !WriteMainRAM ram.bin
# savestates
- input:
    key_code: Key1
    modifiers: null
  action: !ReadSavestate savestate_1.bin
- input:
    key_code: Key2
    modifiers: null
  action: !ReadSavestate savestate_2.bin
- input:
    key_code: Key3
    modifiers: null
  action: !ReadSavestate savestate_3.bin
- input:
    key_code: Key4
    modifiers: null
  action: !ReadSavestate savestate_4.bin
- input:
    key_code: Key5
    modifiers: null
  action: !ReadSavestate savestate_5.bin
- input:
    key_code: Key6
    modifiers: null
  action: !ReadSavestate savestate_6.bin
- input:
    key_code: Key7
    modifiers: null
  action: !ReadSavestate savestate_7.bin
- input:
    key_code: Key8
    modifiers: null
  action: !ReadSavestate savestate_8.bin
- input:
    key_code: Key9
    modifiers: null
  action: !ReadSavestate savestate_9.bin
- input:
    key_code: Key0
    modifiers: null
  action: !ReadSavestate savestate_10.bin
- input:
    key_code: Key1
    modifiers:
      shift: true
      ctrl: false
      alt: false
      logo: false
  action: !WriteSavestate savestate_1.bin
- input:
    key_code: Key2
    modifiers:
      shift: true
      ctrl: false
      alt: false
      logo: false
  action: !WriteSavestate savestate_2.bin
- input:
    key_code: Key3
    modifiers:
      shift: true
      ctrl: false
      alt: false
      logo: false
  action: !WriteSavestate savestate_3.bin
- input:
    key_code: Key4
    modifiers:
      shift: true
      ctrl: false
      alt: false
      logo: false
  action: !WriteSavestate savestate_4.bin
- input:
    key_code: Key5
    modifiers:
      shift: true
      ctrl: false
      alt: false
      logo: false
  action: !WriteSavestate savestate_5.bin
- input:
    key_code: Key6
    modifiers:
      shift: true
      ctrl: false
      alt: false
      logo: false
  action: !WriteSavestate savestate_6.bin
- input:
    key_code: Key7
    modifiers:
      shift: true
      ctrl: false
      alt: false
      logo: false
  action: !WriteSavestate savestate_7.bin
- input:
    key_code: Key8
    modifiers:
      shift: true
      ctrl: false
      alt: false
      logo: false
  action: !WriteSavestate savestate_8.bin
- input:
    key_code: Key9
    modifiers:
      shift: true
      ctrl: false
      alt: false
      logo: false
  action: !WriteSavestate savestate_9.bin
- input:
    key_code: Key0
    modifiers:
      shift: true
      ctrl: false
      alt: false
      logo: false
  action: !WriteSavestate savestate_10.bin
# emulator controls
- input:
    key_code: K
    modifiers: null
  action: !NdsKey A
- input:
    key_code: M
    modifiers: null
  action: !NdsKey B
- input:
    key_code: J
    modifiers: null
  action: !NdsKey X
- input:
    key_code: N
    modifiers: null
  action: !NdsKey Y
- input:
    key_code: W
    modifiers: null
  action: !NdsKey Up
- input:
    key_code: A
    modifiers: null
  action: !NdsKey Left
- input:
    key_code: S
    modifiers: null
  action: !NdsKey Down
- input:
    key_code: D
    modifiers: null
  action: !NdsKey Right
- input:
    key_code: Q
    modifiers: null
  action: !NdsKey L
- input:
    key_code: P
    modifiers: null
  action: !NdsKey R
- input:
    key_code: Space
    modifiers: null
  action: !NdsKey Start
- input:
    key_code: X
    modifiers: null
  action: !NdsKey Select
